version: "3.8"

services:
  # OSRM Backend untuk routing mobil lokal
  osrm-backend:
    image: ghcr.io/project-osrm/osrm-backend:v6.0.0
    container_name: osrm-backend
    volumes:
      - ./data:/data
    ports:
      - "5000:5000"
    command: osrm-routed --algorithm mld /data/java-latest.osrm --max-table-size 10000
    restart: unless-stopped

networks:
  default:
    driver: bridge
